# Required to run your project under the correct environment
language: php

# Versions of PHP you want your project run with
php:
  - '7.1'
  - '7.2'
  - '7.3'

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files
    
# Update composer
before-install:
 - composer self-update

# Commands to be run before your environment runs
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

# Commands you want to run that will verify your build
script: vendor/bin/phpunit
